name = "staffaxis-api"
main = "src/worker.ts"
compatibility_date = "2026-02-01"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "development"

[env.staging]
name = "staffaxis-api-staging"
vars = { NODE_ENV = "staging" }

[env.production]
name = "staffaxis-api-prod"
compatibility_flags = ["nodejs_compat", "enable_nodejs_http_server_modules"]

[env.production.vars]
NODE_ENV = "production"